version: "3.8"
services: 
  database:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "org4"
      POSTGRES_PASSWORD: "org4"
      POSTGRES_DB: "organization4db"
    networks:
      - demo

  patientwebapp:
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DbConnectionSettings:Host: "database"
      DbConnectionSettings:Port: "5432"
      DbConnectionSettings:User: "org4"
      DbConnectionSettings:Password: "org4"
      DbConnectionSettings:Database: "organization4db"
      DbConnectionSettings:RetryCount: 5
      DbConnectionSettings:RetryWaitInSeconds: 30