version: "3.8"
services: 
  database:
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "org4"
      MYSQL_PASSWORD: "org4"
      MYSQL_DATABASE: "organization4db" 
    volumes:
      - data:/var/lib/mysql

  patientwebapp:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnectionSettings:Host: "database"
      DbConnectionSettings:Port: "3306"
      DbConnectionSettings:User: "org4"
      DbConnectionSettings:Password: "org4"
      DbConnectionSettings:Database: "organization4db"
      DbConnectionSettings:RetryCount: 100
      DbConnectionSettings:RetryWaitInSeconds: 30

  intergrationadapters:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnectionSettings:Host: "database"
      DbConnectionSettings:Port: "3306"
      DbConnectionSettings:User: "org4"
      DbConnectionSettings:Password: "org4"
      DbConnectionSettings:Database: "organization4db"
      DbConnectionSettings:RetryCount: 100
      DbConnectionSettings:RetryWaitInSeconds: 30

  editorserver:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnectionSettings:Host: "database"
      DbConnectionSettings:Port: "3306"
      DbConnectionSettings:User: "org4"
      DbConnectionSettings:Password: "org4"
      DbConnectionSettings:Database: "organization4db"
      DbConnectionSettings:RetryCount: 100
      DbConnectionSettings:RetryWaitInSeconds: 30