version: "3.8"
services: 
  database:
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "org4"
      MYSQL_PASSWORD: "org4"
      MYSQL_DATABASE: "organization4db"
    networks:
      - demo
    volumes:
      - sql-scripts:/docker-entrypoint-initdb.d/

  patientwebapp:
    build:
      context: HealthcareSystem\
      dockerfile: Dockerfile.patient-webapp
    ports:
    - "8181:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DBHOST: "database"
      DBPORT: "3306"
      DBUSER: "org4"
      DBPASSWORD: "org4"
      DB: "organization4db"
    depends_on:
      - database
    restart: on-failure
    volumes:
      - sql-scripts:/app/sql
    networks:
      - demo

  intergrationadapters:
    build:
      context: HealthcareSystem\
      dockerfile: Dockerfile.integration-adapters
    ports:
    - "8282:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DBHOST: "database"
      DBPORT: "3306"
      DBUSER: "org4"
      DBPASSWORD: "org4"
      DB: "organization4db"
      RabbitMq:Hostname: "rabbitmq"
      RabbitMq:Username: "org4"
      RabbitMq:Password: "org4"
    depends_on:
      - database
    restart: on-failure
    networks:
      - demo

  editorserver:
    build:
      context: HealthcareSystem\
      dockerfile: Dockerfile.graphical-editorserver
    ports:
    - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DBHOST: "database"
      DBPORT: "3306"
      DBUSER: "org4"
      DBPASSWORD: "org4"
      DB: "organization4db"
    depends_on:
      - database
    restart: on-failure
    networks:
      - demo

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "org4"
      RABBITMQ_DEFAULT_PASS: "org4"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - demo

volumes:
  sql-scripts:

networks:
  demo:
    name: demo
    driver: bridge