database:
  #TODO- implement for postgrade
  image: mysql:8.0.22
  environment:
    MYSQL_ROOT_PASSWORD: "password"
    MYSQL_USER: "org4"
    MYSQL_PASSWORD: "org4"
    MYSQL_DATABASE: "organization4db"
  networks:
    - demo
  volumes:
    - sql-scripts:/docker-entrypoint-initdb.d/
