version: "3.8"
services: 
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "org4"
      POSTGRES_DATABASE: "organization4db"
    networks:
      - demo