version: "3.8"
services: 
  database:
    image: mysql
    ports:
      - "8001:5432"
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  patientwebapp:
    build:
      context: HealthcareSystem\
      dockerfile: Dockerfile.patient-webapp
    ports:
    - "8181:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DBHOST: "database"
      DBPORT: "3306"
      DBUSER: "root"
      DBPASSWORD: "root"
      DB: "organization4db"
    depends_on:
      - mysqldb
    restart: always

  intergrationadapters:
    build:
      context: HealthcareSystem\
      dockerfile: Dockerfile.integration-adapters
    ports:
    - "8282:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DBHOST: "database"
      DBPORT: "3306"
      DBUSER: "root"
      DBPASSWORD: "root"
      DB: "organization4db"
    depends_on:
      - mysqldb
    restart: always

  editorserver:
    build:
      context: HealthcareSystem\
      dockerfile: Dockerfile.graphical-editorserver
    ports:
    - "8383:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DBHOST: "database"
      DBPORT: "3306"
      DBUSER: "root"
      DBPASSWORD: "root"
      DB: "organization4db"
    depends_on:
      - mysqldb
    restart: always