trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Set-Location "./HealthcareSystem"
      dotnet new sln --name temp
      dotnet sln temp.sln add "HealthcareSystem/DoctorFrontend/DoctorFrontend.csproj"
      dotnet sln temp.sln add "HealthcareSystem/ManagerFrontend/ManagerFrontend.csproj"
      dotnet sln temp.sln add "HealthcareSystem/SecretaryFrontend/SecretaryFrontend.csproj"
      dotnet sln temp.sln add "HealthcareSystem/PatientFrontend/PatientFrontend.csproj"
      dotnet sln temp.sln add "HealthcareSystem/GraphicalEditor/GraphicalEditor.csproj"
      dotnet sln temp.sln add "HealthcareSystem/LegacyBackend/LegacyBackend.csproj"
    pwsh: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'NuGet package restore'
  inputs:
    restoreSolution: 'temp.sln'
    

- task: VSBuild@1
  displayName: 'Build WPFs'
  inputs:
    solution: 'temp.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

