trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  paths: "**/LegacyBackend/* **/GraphicalEditor/* **/PatientFrontend/* **/ManagerFrontend/* **/SecretaryFrontend/* **/DoctorFrontend/*"
  solution: 'HealthcareSystem/temp.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Check
  steps:
  - task: PowerShell@2
    displayName: 'Check if build is needed'
    name: CheckChangedFiles
    inputs:
      targetType: 'inline'
      script: |
        # 
        $files=$(git diff HEAD HEAD~ --name-only)
        $paths = $env:PATHS -split ' '
        $paths
        
        $shouldBuild = $false

        foreach ($path in $paths) 
        { 
            if( $files -like $path) 
            {
                $shouldBuild = $true
                break
            } 
        }

        if ($shouldBuild)
        {
            Write-Host "##vso[task.setvariable variable=shouldBuild;isOutput=true]Yes"
        }
        else
        {
            Write-Host "##vso[task.setvariable variable=shouldBuild;isOutput=true]No"
        }
      pwsh: true

- job: Build
  dependsOn: Check
  condition: eq(dependencies.Check.outputs['CheckChangedFiles.shouldBuild'], 'Yes')
  steps:
  - task: PowerShell@2
    displayName: 'Create temp sln'
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Set-Location "./HealthcareSystem"
        dotnet new sln --name temp
        dotnet sln temp.sln add "DoctorFrontend/DoctorFrontend.csproj"
        dotnet sln temp.sln add "ManagerFrontend/ManagerFrontend.csproj"
        dotnet sln temp.sln add "SecretaryFrontend/SecretaryFrontend.csproj"
        dotnet sln temp.sln add "PatientFrontend/PatientFrontend.csproj"
        dotnet sln temp.sln add "GraphicalEditor/GraphicalEditor.csproj"
        dotnet sln temp.sln add "LegacyBackend/LegacyBackend.csproj"
        Set-Location ".."
      pwsh: true

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: 'NuGet package restore'
    inputs:
      restoreSolution: '$(solution)'
      

  - task: VSBuild@1
    displayName: 'Build WPFs'
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

