version: "3.8"
services: 
  database:
    image: seeded-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "org4"
      MYSQL_PASSWORD: "org4"
      MYSQL_DATABASE: "organization4db" 

  graphicaleditorserver:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnectionSettings:Host: "database"
      DbConnectionSettings:Port: "3306"
      DbConnectionSettings:User: "org4"
      DbConnectionSettings:Password: "org4"
      DbConnectionSettings:Database: "organization4db"
      DbConnectionSettings:RetryCount: 5
      DbConnectionSettings:RetryWaitInSeconds: 30

  userservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnectionSettings:Host: "database"
      DbConnectionSettings:Port: "3306"
      DbConnectionSettings:User: "org4"
      DbConnectionSettings:Password: "org4"
      DbConnectionSettings:Database: "organization4db"
      DbConnectionSettings:RetryCount: 5
      DbConnectionSettings:RetryWaitInSeconds: 30

  patientservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnectionSettings:Host: "database"
      DbConnectionSettings:Port: "3306"
      DbConnectionSettings:User: "org4"
      DbConnectionSettings:Password: "org4"
      DbConnectionSettings:Database: "organization4db"
      DbConnectionSettings:RetryCount: 5
      DbConnectionSettings:RetryWaitInSeconds: 30

  scheduleservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbConnectionSettings:Host: "database"
      DbConnectionSettings:Port: "3306"
      DbConnectionSettings:User: "org4"
      DbConnectionSettings:Password: "org4"
      DbConnectionSettings:Database: "organization4db"
      DbConnectionSettings:RetryCount: 5
      DbConnectionSettings:RetryWaitInSeconds: 30