version: "3.8"
services: 
  database:
    build:
      context: ../../HealthcareSystem/Backend
      dockerfile: Dockerfile.postgre
    environment:
      POSTGRES_USER: "org4"
      POSTGRES_PASSWORD: "org4"
      POSTGRES_DB: "organization4db"
    restart: always
    networks:
      - psw

  esdatabase:
    build:
      context: ../../HealthcareSystem/EventSourcingService
      dockerfile: Dockerfile.postgre
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      POSTGRES_USER: "org4"
      POSTGRES_PASSWORD: "org4"
      POSTGRES_DB: "organization4db"
    restart: always
    networks:
      - psw

  intergrationadapters:
    build:
      context: ../../HealthcareSystem/IntegrationAdapters
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 20
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
      TENDER_SERVICE_URL: "http://tenderservice"
      ACTION_BENEFIT_SERVICE_URL: "http://actionbenefitservice"
      PHARMACY_SYSTEM_SERVICE_URL: "http://pharmacysystemservice"
      DRUG_SERVICE_URL: "http://drugservice"
    depends_on:      
      - database
    restart: on-failure
    networks:
      - psw

  drugservice:
    build:
      context: ../../HealthcareSystem/IADrugService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
      TENDER_SERVICE_URL: "http://tenderservice"
      ACTION_BENEFIT_SERVICE_URL: "http://actionbenefitserviceservice"
      PHARMACY_SYSTEM_SERVICE_URL: "http://pharmacysystemservice"
      DRUG_SERVICE_URL: "http://drugservice"
    depends_on:
      - database
    restart: on-failure
    networks:
      - psw

  pharmacysystemservice:
    build:
      context: ../../HealthcareSystem/IAPharmacySystemService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
      TENDER_SERVICE_URL: "http://tenderservice"
      ACTION_BENEFIT_SERVICE_URL: "http://actionbenefitserviceservice"
      PHARMACY_SYSTEM_SERVICE_URL: "http://pharmacysystemservice"
      DRUG_SERVICE_URL: "http://drugservice"
    depends_on:
      - database
    restart: on-failure
    networks:
      - psw

  actionbenefitservice:
    build:
      context: ../../HealthcareSystem/IAActionBenefitService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "org4"
      RABBITMQ_PASSWORD: "org4"
      RABBITMQ_RETRY: 20
      RABBITMQ_RETRY_WAIT: 30000
      TENDER_SERVICE_URL: "http://tenderservice"
      ACTION_BENEFIT_SERVICE_URL: "http://actionbenefitserviceservice"
      PHARMACY_SYSTEM_SERVICE_URL: "http://pharmacysystemservice"
      DRUG_SERVICE_URL: "http://drugservice"
    depends_on:
      - database
      - rabbitmq
    restart: on-failure
    networks:
      - psw
      - demo

  tenderservice:
    build:
      context: ../../HealthcareSystem/IATenderService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "org4"
      RABBITMQ_PASSWORD: "org4"
      RABBITMQ_RETRY: 20
      RABBITMQ_RETRY_WAIT: 30000
      TENDER_SERVICE_URL: "http://tenderservice"
      ACTION_BENEFIT_SERVICE_URL: "http://actionbenefitserviceservice"
      PHARMACY_SYSTEM_SERVICE_URL: "http://pharmacysystemservice"
      DRUG_SERVICE_URL: "http://drugservice"
    depends_on:
      - database
      - rabbitmq
    restart: on-failure
    networks:
      - psw
      - demo

  patientwebapp:
    build:
      context: ../../HealthcareSystem/PatientWebApp
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      PATIENT_SERVICE_URL: "http://patientservice"
      FEEDBACK_SURVEY_SERVICE_URL: "http://feedbacksurveyservice"
      USER_SERVICE_URL: "http://userservice"
      NOTIFICATION_SERVICE_URL: "http://notificationservice"
      SCHEDULE_SERVICE_URL: "http://scheduleservice"
      EVENT_SOURCING_SERVICE_URL: "http://esservice"
    depends_on:
      - userservice
      - patientservice
      - notificationservice
      - feedbacksurveyservice
      - scheduleservice
      - esservice
    restart: on-failure
    networks:
      - psw

  graphicaleditorserver:
    build:
      context: ../../HealthcareSystem/GraphicalEditorServer
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
      PATIENT_SERVICE_URL: "http://patientservice"
      USER_SERVICE_URL: "http://userservice"
      SCHEDULE_SERVICE_URL: "http://scheduleservice"
      EVENT_SOURCING_SERVICE_URL: "http://esservice"
    depends_on:
      - userservice
      - patientservice
      - scheduleservice
      - esservice
    restart: on-failure
    networks:
      - psw

  esservice:
    build:
      context: ../../HealthcareSystem/EventSourcingService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@esdatabase:5432/organization4db"
    depends_on:
      - database
    restart: on-failure
    networks:
      - psw

  userservice:
    build:
      context: ../../HealthcareSystem/UserService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
    depends_on:
      - database
    restart: on-failure
    networks:
      - psw

  scheduleservice:
    build:
      context: ../../HealthcareSystem/ScheduleService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
    depends_on:
      - database
    restart: on-failure
    networks:
      - psw

  patientservice:
    build:
      context: ../../HealthcareSystem/PatientService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
    depends_on:
      - database
    restart: on-failure
    networks:
      - psw

  feedbacksurveyservice:
    build:
      context: ../../HealthcareSystem/FeedbackAndSurveyService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 5
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
    depends_on:
      - database
    restart: on-failure
    networks:
      - psw

  notificationservice:
    build:
      context: ../../HealthcareSystem/NotificationService
      dockerfile: Dockerfile.local
    restart: on-failure
    networks:
      - psw

networks:
  psw:
    name: psw
    driver: bridge