trigger:
  branches:
    include:
    - develop
pr: none

stages:
- stage: Prepare
  displayName: Prepare for tests
  jobs:  
  - job: ResetDb
    displayName: Reset database
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - task: PowerShell@2
        displayName: "Generate SQL script"
        inputs:
          targetType: 'inline'
          script: |
            echo "----- Installing EF Core. -----"
            dotnet tool install dotnet-ef --version 3.1.9
            echo "----- Generating script. -----"
            dotnet-ef dbcontext script -c "TestDbContext" -p "./HealthcareSystem/Backend/Backend.csproj" -o init.sql
          pwsh: true
      - task: PowerShell@2
        displayName: "Initialize Heroku Postgres"
        inputs:
          targetType: 'inline'
          script: |
            echo "----- Reseting database. -----"
            heroku pg:reset DATABASE_URL --app vlaksi-patient-service --confirm vlaksi-patient-service
            echo "----- Initializing database. -----"
            Get-Content init.sql | heroku pg:psql DATABASE_URL --app vlaksi-patient-service
          pwsh: true     
  - job: Wait
    dependsOn: ResetDb
    displayName: Wait for component redeployments
    pool: Server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '5' 

- stage: Smoke
  displayName: Run smoke tests
  pool:
    vmImage: 'ubuntu-18.04'
  jobs:
  - job: UserService
    steps:
      - task: PowerShell@2
        displayName: "Ping test"
        inputs:
          filePath: 'pipelines/cd/smoke.ps1'
          arguments: '-uri https://$vlaksi-user-service.herokuapp.com/api/ping -code 200'
          pwsh: true
      - task: PowerShell@2
        displayName: "Database connection test"
        inputs:
          filePath: 'pipelines/cd/smoke.ps1'
          arguments: '-uri https://$vlaksi-user-service.herokuapp.com/api/countries -code 200'
          pwsh: true

  - job: FeedbackAndSurveyService
    steps:
      - task: PowerShell@2
        displayName: "Ping test"
        inputs:
          filePath: 'pipelines/cd/smoke.ps1'
          arguments: '-uri https://$vlaksi-feedback-and-survey.herokuapp.com/api/ping -code 200'
          pwsh: true
      - task: PowerShell@2
        displayName: "Database connection test"
        inputs:
          filePath: 'pipelines/cd/smoke.ps1'
          arguments: '-uri https://$vlaksi-feedback-and-survey.herokuapp.com/api/feedback/published -code 200'
          pwsh: true

  - job: NotificationService
    steps:
      - task: PowerShell@2
        displayName: "Ping test"
        inputs:
          filePath: 'pipelines/cd/smoke.ps1'
          arguments: '-uri https://$vlaksi-notification-service.herokuapp.com/api/ping -code 200'
          pwsh: true

  - job: PatientService
    steps:
      - task: PowerShell@2
        displayName: "Ping test"
        inputs:
          filePath: 'pipelines/cd/smoke.ps1'
          arguments: '-uri https://$vlaksi-patient-service.herokuapp.com/api/ping -code 200'
          pwsh: true

  - job: ApiGateway
    steps:
      - task: PowerShell@2
        displayName: "Ping test"
        inputs:
          filePath: 'pipelines/cd/smoke.ps1'
          arguments: '-uri https://$vlaksi-patientwebapp.herokuapp.com/api/ping -code 200'
          pwsh: true


- stage: E2E
  displayName: Run E2E tests
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    e2etests: 'HealthcareSystem/E2ETests/E2ETests.csproj'
  jobs:
  - job: Test
    steps:
    - task: PowerShell@2
      displayName: 'Run tests'
      inputs:
        targetType: 'inline'
        script: |
          #
          dotnet test $(e2etests)