FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

# MOVE OUR BACKEND TO THE CONTAINER
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Backend/Backend.csproj", "Backend/"]
WORKDIR "/src/Backend"
COPY "Backend/" .

# MOVE OUR ASP.NET WEB APP TO THE CONTAINER
WORKDIR /src
COPY ["GraphicalEditorServer/GraphicalEditorServer.csproj", "GraphicalEditorServer/"]
WORKDIR "/src/GraphicalEditorServer"
COPY "GraphicalEditorServer/" .

FROM build AS publish
RUN dotnet publish "GraphicalEditorServer.csproj" -c Release -o /app/publish

# BUILD RUNTIME IMAGE
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GraphicalEditorServer.dll"]
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet PatientWebApp.dll
