version: "3.8"
services: 
  database:
    image: seeded-postgre
    environment:
      POSTGRES_USER: "org4"
      POSTGRES_PASSWORD: "org4"
      POSTGRES_DB: "organization4db"
    restart: always
    networks:
      - demo  

  patientwebapp:
    build:
      context: PatientWebApp
      dockerfile: Dockerfile.local
    ports:
    - "8181:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 10
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
      PATIENT_SERVICE_URL: "http://patientservice"
      FEEDBACK_SURVEY_SERVICE_URL: "http://feedbacksurveyservice"
    depends_on:
      - database
    restart: on-failure
    networks:
      - demo

  patientservice:
    build:
      context: PatientService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 10
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
    depends_on:
      - database
    restart: on-failure
    networks:
      - demo

  feedbacksurveyservice:
    build:
      context: FeedbackAndSurveyService
      dockerfile: Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Test
      DATABASE_RETRY: 10
      DATABASE_RETRY_WAIT: 30
      DATABASE_URL: "postgres://org4:org4@database:5432/organization4db"
    depends_on:
      - database
    restart: on-failure
    networks:
      - demo


networks:
  demo:
    name: demo
    driver: bridge