FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src/Backend
COPY Backend/ .
WORKDIR /src/GraphicalEditorServer
COPY GraphicalEditorServer/ .

FROM build AS publish
RUN dotnet publish "GraphicalEditorServer.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GraphicalEditorServer.dll"]
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet PatientWebApp.dll
