CREATE TABLE "Countries" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
);

CREATE TABLE "DrugsInRooms" (
    "DrugId" integer NOT NULL,
    "RoomNumber" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_DrugsInRooms" PRIMARY KEY ("RoomNumber", "DrugId")
);

CREATE TABLE "DrugTypes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Type" text NULL,
    "Purpose" text NULL,
    CONSTRAINT "PK_DrugTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "EquipmentsInRooms" (
    "IdEquipment" integer NOT NULL,
    "RoomNumber" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_EquipmentsInRooms" PRIMARY KEY ("RoomNumber", "IdEquipment")
);

CREATE TABLE "EquipmentTypes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "IsConsumable" boolean NOT NULL,
    CONSTRAINT "PK_EquipmentTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Ingridients" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Alergen" boolean NOT NULL,
    CONSTRAINT "PK_Ingridients" PRIMARY KEY ("Id")
);

CREATE TABLE "Pharmacies" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "ApiKey" character varying(255) NOT NULL,
    "Url" character varying(255) NOT NULL,
    "ActionsBenefitsExchangeName" character varying(255) NULL,
    "ActionsBenefitsSubscribed" boolean NOT NULL,
    "GrpcHost" character varying(255) NULL,
    "GrpcPort" integer NOT NULL,
    CONSTRAINT "PK_Pharmacies" PRIMARY KEY ("Id")
);

CREATE TABLE "Rooms" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Usage" integer NOT NULL,
    "Capacity" integer NOT NULL,
    "Occupation" integer NOT NULL,
    "Renovation" boolean NOT NULL,
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
);

CREATE TABLE "Specialties" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Specialties" PRIMARY KEY ("Id")
);

CREATE TABLE "Cities" (
    "ZipCode" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "CountryId" integer NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("ZipCode"),
    CONSTRAINT "FK_Cities_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Drugs" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DrugType_Id" integer NOT NULL,
    "Name" text NULL,
    "Quantity" integer NOT NULL,
    "ExpirationDate" timestamp without time zone NOT NULL,
    "Producer" text NULL,
    CONSTRAINT "PK_Drugs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Drugs_DrugTypes_DrugType_Id" FOREIGN KEY ("DrugType_Id") REFERENCES "DrugTypes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Equipment" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Quantity" integer NOT NULL,
    "TypeId" integer NOT NULL,
    CONSTRAINT "PK_Equipment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Equipment_EquipmentTypes_TypeId" FOREIGN KEY ("TypeId") REFERENCES "EquipmentTypes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ActionsBenefits" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PharmacyId" integer NOT NULL,
    "Subject" text NOT NULL,
    "Message" text NOT NULL,
    "IsPublic" boolean NOT NULL,
    CONSTRAINT "PK_ActionsBenefits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ActionsBenefits_Pharmacies_PharmacyId" FOREIGN KEY ("PharmacyId") REFERENCES "Pharmacies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RenovationPeriods" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoomNumber" integer NOT NULL,
    "BeginDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_RenovationPeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RenovationPeriods_Rooms_RoomNumber" FOREIGN KEY ("RoomNumber") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
);

CREATE TABLE "User" (
    "Jmbg" text NOT NULL,
    "Name" text NULL,
    "Surname" text NULL,
    "Gender" integer NOT NULL,
    "DateOfBirth" timestamp without time zone NOT NULL,
    "Phone" text NULL,
    "Email" text NULL,
    "CityZipCode" integer NOT NULL,
    "HomeAddress" text NULL,
    "Username" text NULL,
    "Password" text NULL,
    "Discriminator" text NOT NULL,
    "NumberOfLicence" text NULL,
    "DateOfEmployment" timestamp without time zone NULL,
    "DoctorsOfficeId" integer NULL,
    "DateOfRegistration" timestamp without time zone NULL,
    "IsBlocked" boolean NULL,
    "IsActive" boolean NULL,
    "ImageName" text NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Jmbg"),
    CONSTRAINT "FK_User_Rooms_DoctorsOfficeId" FOREIGN KEY ("DoctorsOfficeId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_User_Cities_CityZipCode" FOREIGN KEY ("CityZipCode") REFERENCES "Cities" ("ZipCode") ON DELETE CASCADE
);

CREATE TABLE "DrugConsumptions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DrugId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_DrugConsumptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DrugConsumptions_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES "Drugs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DoctorSpecialties" (
    "DoctorJmbg" text NOT NULL,
    "SpecialtyId" integer NOT NULL,
    CONSTRAINT "PK_DoctorSpecialties" PRIMARY KEY ("DoctorJmbg", "SpecialtyId"),
    CONSTRAINT "FK_DoctorSpecialties_User_DoctorJmbg" FOREIGN KEY ("DoctorJmbg") REFERENCES "User" ("Jmbg") ON DELETE CASCADE,
    CONSTRAINT "FK_DoctorSpecialties_Specialties_SpecialtyId" FOREIGN KEY ("SpecialtyId") REFERENCES "Specialties" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Feedbacks" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SendingDate" timestamp without time zone NOT NULL,
    "Comment" text NULL,
    "IsPublished" boolean NOT NULL,
    "IsAllowedToPublish" boolean NOT NULL,
    "CommentatorJmbg" text NULL,
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Feedbacks_User_CommentatorJmbg" FOREIGN KEY ("CommentatorJmbg") REFERENCES "User" ("Jmbg") ON DELETE RESTRICT
);

CREATE TABLE "PatientCards" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BloodType" integer NOT NULL,
    "RhFactor" integer NOT NULL,
    "Alergies" text NULL,
    "MedicalHistory" text NULL,
    "HasInsurance" boolean NOT NULL,
    "Lbo" text NULL,
    "PatientJmbg" text NULL,
    CONSTRAINT "PK_PatientCards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PatientCards_User_PatientJmbg" FOREIGN KEY ("PatientJmbg") REFERENCES "User" ("Jmbg") ON DELETE RESTRICT
);

CREATE TABLE "WorkingTimes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DoctorJmbg" text NULL,
    "WorkShift" integer NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_WorkingTimes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkingTimes_User_DoctorJmbg" FOREIGN KEY ("DoctorJmbg") REFERENCES "User" ("Jmbg") ON DELETE RESTRICT
);

CREATE TABLE "Examinations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Type" integer NOT NULL,
    "DateAndTime" timestamp without time zone NOT NULL,
    "Anamnesis" text NULL,
    "DoctorJmbg" text NULL,
    "IdRoom" integer NOT NULL,
    "IdPatientCard" integer NOT NULL,
    "ExaminationStatus" integer NOT NULL,
    "IsSurveyCompleted" boolean NOT NULL,
    CONSTRAINT "PK_Examinations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Examinations_User_DoctorJmbg" FOREIGN KEY ("DoctorJmbg") REFERENCES "User" ("Jmbg") ON DELETE RESTRICT,
    CONSTRAINT "FK_Examinations_PatientCards_IdPatientCard" FOREIGN KEY ("IdPatientCard") REFERENCES "PatientCards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Examinations_Rooms_IdRoom" FOREIGN KEY ("IdRoom") REFERENCES "Rooms" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SurveysAboutDoctor" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BehaviorOfDoctor" integer NOT NULL,
    "DoctorProfessionalism" integer NOT NULL,
    "GettingAdviceByDoctor" integer NOT NULL,
    "AvailabilityOfDoctor" integer NOT NULL,
    "ExaminationId" integer NOT NULL,
    CONSTRAINT "PK_SurveysAboutDoctor" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SurveysAboutDoctor_Examinations_ExaminationId" FOREIGN KEY ("ExaminationId") REFERENCES "Examinations" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SurveysAboutHospital" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nursing" integer NOT NULL,
    "Cleanliness" integer NOT NULL,
    "OverallRating" integer NOT NULL,
    "SatisfiedWithDrugAndInstrument" integer NOT NULL,
    "ExaminationId" integer NOT NULL,
    CONSTRAINT "PK_SurveysAboutHospital" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SurveysAboutHospital_Examinations_ExaminationId" FOREIGN KEY ("ExaminationId") REFERENCES "Examinations" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SurveysAboutMedicalStaff" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BehaviorOfMedicalStaff" integer NOT NULL,
    "MedicalStaffProfessionalism" integer NOT NULL,
    "GettingAdviceByMedicalStaff" integer NOT NULL,
    "EaseInObtainingFollowUpInformation" integer NOT NULL,
    "ExaminationId" integer NOT NULL,
    CONSTRAINT "PK_SurveysAboutMedicalStaff" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SurveysAboutMedicalStaff_Examinations_ExaminationId" FOREIGN KEY ("ExaminationId") REFERENCES "Examinations" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Therapies" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Diagnosis" text NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "DailyDose" integer NOT NULL,
    "IdDrug" integer NOT NULL,
    "IdExamination" integer NOT NULL,
    CONSTRAINT "PK_Therapies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Therapies_Drugs_IdDrug" FOREIGN KEY ("IdDrug") REFERENCES "Drugs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Therapies_Examinations_IdExamination" FOREIGN KEY ("IdExamination") REFERENCES "Examinations" ("Id") ON DELETE CASCADE
);

INSERT INTO "Countries" ("Id", "Name")
VALUES (1, 'Srbija');

INSERT INTO "Cities" ("ZipCode", "CountryId", "Name")
VALUES (21000, 1, 'Novi Sad');

CREATE INDEX "IX_ActionsBenefits_PharmacyId" ON "ActionsBenefits" ("PharmacyId");

CREATE INDEX "IX_Cities_CountryId" ON "Cities" ("CountryId");

CREATE INDEX "IX_DoctorSpecialties_SpecialtyId" ON "DoctorSpecialties" ("SpecialtyId");

CREATE INDEX "IX_DrugConsumptions_DrugId" ON "DrugConsumptions" ("DrugId");

CREATE INDEX "IX_Drugs_DrugType_Id" ON "Drugs" ("DrugType_Id");

CREATE INDEX "IX_Equipment_TypeId" ON "Equipment" ("TypeId");

CREATE INDEX "IX_Examinations_DoctorJmbg" ON "Examinations" ("DoctorJmbg");

CREATE INDEX "IX_Examinations_IdPatientCard" ON "Examinations" ("IdPatientCard");

CREATE INDEX "IX_Examinations_IdRoom" ON "Examinations" ("IdRoom");

CREATE INDEX "IX_Feedbacks_CommentatorJmbg" ON "Feedbacks" ("CommentatorJmbg");

CREATE UNIQUE INDEX "IX_PatientCards_PatientJmbg" ON "PatientCards" ("PatientJmbg");

CREATE UNIQUE INDEX "IX_Pharmacies_ActionsBenefitsExchangeName" ON "Pharmacies" ("ActionsBenefitsExchangeName");

CREATE INDEX "IX_RenovationPeriods_RoomNumber" ON "RenovationPeriods" ("RoomNumber");

CREATE UNIQUE INDEX "IX_SurveysAboutDoctor_ExaminationId" ON "SurveysAboutDoctor" ("ExaminationId");

CREATE UNIQUE INDEX "IX_SurveysAboutHospital_ExaminationId" ON "SurveysAboutHospital" ("ExaminationId");

CREATE UNIQUE INDEX "IX_SurveysAboutMedicalStaff_ExaminationId" ON "SurveysAboutMedicalStaff" ("ExaminationId");

CREATE INDEX "IX_Therapies_IdDrug" ON "Therapies" ("IdDrug");

CREATE INDEX "IX_Therapies_IdExamination" ON "Therapies" ("IdExamination");

CREATE INDEX "IX_User_DoctorsOfficeId" ON "User" ("DoctorsOfficeId");

CREATE INDEX "IX_User_CityZipCode" ON "User" ("CityZipCode");

CREATE INDEX "IX_WorkingTimes_DoctorJmbg" ON "WorkingTimes" ("DoctorJmbg");

